### ISSUE TITLE
when i use this to deploy Rocket.Chat, i got a error 

### ISSUE THREAD

**Issue by ghost** [jshimko/meteor-launchpad#100]
![screen shot 2018-03-27 at 9 40 15 am](https://user-images.githubusercontent.com/19723961/37941870-fd4c9d50-31a2-11e8-8c8a-57bb0dc6b8b6.png)

**Comment by jshimko** [comment]
Rocket Chat has its own officially supported Dockerfile and build.  Any reason you're not using that?

https://github.com/RocketChat/Rocket.Chat/blob/develop/.docker/Dockerfile

I don't know anything about their build requirements and I assume you're trying to build a custom image that isn't the same as their official release.  You should probably file an issue in their repo and ask how to build a custom image.  Sorry I don't have a better answer for you.
