### ISSUE TITLE
How to use with METEOR_PACKAGE_DIRS env var

### ISSUE THREAD

**Issue by Fabiencdp** [jshimko/meteor-launchpad#119]
Hi! 
I have two meteor project that share same packages directories and settings files from their parent directory. 

```
- basedir
     - settings.json
     - packages/
     - project1/
     - project2/
```
The "packages" folder contain my custom meteor packages that are shared between the two app. 
 I use a env file to specify the path, as meteor documentation said: 
`METEOR_PACKAGE_DIRS=../packages`
But i don't know how to do the same with a docker-compose and this image.

Here is a way to reproduce the same behaviors, if not, did you have a better idea for that kind of structure? 

Thanks for your help!

**Comment by jshimko** [comment]
Unfortunately, I think you're going to need to create your own Docker build to accomplish that.  This project doesn't have an easy solution for handling multiple Meteor builds in custom directories.  It expects you to have the Dockerfile in the root of your app.

One quick and easy solution (even if it's a little bit of a hack) would be to just create a bash script that copies your external files into each project at build time, runs the two Docker builds, then cleans up those copied files.  Not exactly the prettiest solution, but it could probably be done in less than a dozen lines of code.

**Comment by Fabiencdp** [comment]
Yes, i gonna do the hack for the moment.

Thanks for your answer!
