### ISSUE TITLE
Adding settings.json to .dockerignore?

### ISSUE THREAD

**Issue by iehdk** [jshimko/meteor-launchpad#127]
I suppose it is in order to add `settings.json` to the `.dockerignore` file to avoid having sensitive data, i.e. passwords, copied to the image. Instead one should provide the settings via environment variables at run time with:

```
$ docker run -d \
  -e METEOR_SETTINGS="$(cat settings.json)" \
  ...
```

**Comment by jshimko** [comment]
Yes, that is definitely what you want.  I recommend sticking with environment variables whenever possible.  Once a meteor app is built into a production bundle, Meteor settings files are no longer as useful.

So... this isn't really an issue with this image, right?  This is an implementation detail that happens later after you've built your app.  That said, I'm going to close this.

**Comment by iehdk** [comment]
It would be nice to add to the documentation on the dockerignore:

```
.git
.meteor/local
node_modules
# Don't commit Meteor settings file with sensitive data (i.e. passwords)
settings.json
```
