### ISSUE TITLE
can't find entrypoint.sh

### ISSUE THREAD

**Issue by msramalho** [jshimko/meteor-launchpad#128]
I know this question has been asked in #38 but the answer is unsatisfactory and I have spent hours trying to get this image up and running. Here is my dockerfile and the error I get:

![image](https://user-images.githubusercontent.com/19508417/49908407-4a3c6900-fe72-11e8-8453-b8b6d151f5ed.png)

I have only changed `80:3000` to `3000:3000` and commented the `ROOT_URL` setting.

My `.meteor/.platforms` looks like this:

```
server
browser
```

**Comment by jshimko** [comment]
You're trying to run `jshimko/meteor-launchpad:latest` (line 2).  That's not a thing.  This project is just a build utility, not an app that can run.  You need to switch that line out to be your built app image.

**Comment by msramalho** [comment]
You are correct, I have done it and it works. 

For future reference:
 * building local image from `jshimko/meteor-launchpad:latest`
 * using the image name in the `docker_compose.yml`
