### ISSUE TITLE
'p80.pool.sks-keyservers.net: Host not found'

### ISSUE THREAD

**Issue by gustawdaniel** [jshimko/meteor-launchpad#139]
I have error

```
`/tmp/tmp.yxHxdeATKO/pubring.gpg' created\", '\\x1b[0m', '\\x1b[91mgpg: \\x1b[0m', '\\x1b[91mrequesting key BF357DD4 from hkp server p80.pool.sks-keyservers.net', '\\x1b[0m', '?: ', 'p80.pool.sks-keyservers.net: Host not found', \"gpgkeys: HTTP fetch error 7: couldn't connect: Success\", '\\x1b[91mgpg: \\x1b[0m', '\\x1b[91mno valid OpenPGP data found.', '\\x1b[0m', '\\x1b[91mgpg: \\x1b[0m', '\\x1b[91mTotal number processed: 0', 
```

Is this package maintained?

**Comment by gustawdaniel** [comment]
To fix this issue only action required is accept this pull request

https://github.com/jshimko/meteor-launchpad/pull/134

**Comment by jshimko** [comment]
Merged.  Thanks!

I don't actively maintain this project anymore since I no longer use Meteor, but I may consider updating things since it appears a lot of people still use it.  Let me know if things work now that the PR has been merged.

**Comment by gustawdaniel** [comment]
Works perfectly :D thanks!

I can use it typing these lines:

```
    - mkdir -p local
    - cd local
    - git clone https://github.com/jshimko/meteor-launchpad.git
    - cd meteor-launchpad
    - ./build.sh jshimko/meteor-launchpad
    - cd ../..
```

In my `ci/cd`.

I will be able to remove them if you push these changes to docker hub

https://hub.docker.com/r/jshimko/meteor-launchpad

**Comment by jshimko** [comment]
Done.  

```dockerfile
FROM jshimko/meteor-launchpad:v2.4.0

...
```
