### ISSUE TITLE
Add support for git urls in package.json by installing git

### ISSUE THREAD

**Issue by Jank1310** [jshimko/meteor-launchpad#16]
Please add `git` to `install-deps.sh` to add support for public and private git repositories in package.json like: `git+https://github.com/Jank1310/XYZ.git`

```
apt-get install -y --no-install-recommends curl ca-certificates bzip2 build-essential numactl python wget git
```

P.S. Thank you for making this image :+1:

**Comment by jshimko** [comment]
Did that fail for you?  I thought npm was capable of doing that itself.  I'm pretty sure I've used this image with an app that had npm deps on github.

**Comment by jshimko** [comment]
Never mind.  I just confirmed it definitely doesn't work.

Fixed.  :)
