### ISSUE TITLE
Make meteor-launchpad the reference meteor implementation?

### ISSUE THREAD

**Issue by 0o-de-lally** [jshimko/meteor-launchpad#18]
I think you're doing a great job maintaining this image. I vote for it to be the foundation of the meteor reference implementation as discussed here:

https://forums.meteor.com/t/docker-team-up-to-create-a-reference-docker-image-for-meteor/30829/26

@jshimko  Can we get your input on this thread? :)

**Comment by jshimko** [comment]
This is now the first recommended Docker base image on the Meteor guide.

https://guide.meteor.com/deployment.html#docker

...and the only one of those 3 that's even maintained. So, I guess it's reasonably safe to say this is now the "reference implementation".  

Thanks!
