### ISSUE TITLE
/opt/build_scripts/build-meteor.sh: line 17:    65 Killed

### ISSUE THREAD

**Issue by nzwade** [jshimko/meteor-launchpad#2]
Hey @jshimko ,

Thanks for taking the time to put this together. I'm trying to migrate from mup to meteor-launchpad but I'm hitting the below error when building the image, do you have any ideas on how I can resolve this?

> docker build -t nzwade/portfoliorobot_meteor:latest .
> Sending build context to Docker daemon 79.26 MB
> Step 1 : FROM jshimko/meteor-launchpad:latest
> 
> Executing 2 build triggers...
> Step 1 : COPY . $APP_SOURCE_DIR
> Step 1 : RUN cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
>  ---> Running in 130abcb98d36
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100  7786    0  7786    0     0  18393      0 --:--:-- --:--:-- --:--:-- 18450
> 
> [-] Installing Meteor 1.4.1.2...
> 
> Downloading Meteor distribution
> 
> Meteor 1.4.1.2 has been installed in your home directory (~/.meteor).
> Writing a launcher script to /usr/local/bin/meteor for your convenience.
> 
> To get started fast:
> 
>   $ meteor create ~/my_cool_app
>   $ cd ~/my_cool_app
>   $ meteor
> 
> Or see the docs at:
> 
>   docs.meteor.com
> 
> [-] Building Meteor application...
> 
> npm WARN portfoliorobot_meteor@1.0.0 No description
> npm WARN portfoliorobot_meteor@1.0.0 No repository field.
> /opt/build_scripts/build-meteor.sh: line 17:    65 Killed                  meteor build --directory $APP_BUNDLE_DIR
> The command '/bin/sh -c cd $APP_SOURCE_DIR &&             bash $BUILD_SCRIPTS_DIR/install-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/build-meteor.sh &&             bash $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 137

My dev environment is MacOS, for deployment I copied all the Meteor files over to my Ubuntu virtual machine (excluding the .meteor/local file) and ran the above in terminal.

Let me know if I can provide anything else that will help

**Comment by jshimko** [comment]
Nobody else appears to be having this problem so it sounds like an issue with your build environment or your app code.  Also, I think the 137 exit code might be an "insufficient memory" error (based on this [quick Google search](https://www.google.com/search?q=non-zero+code%3A+137&oq=non-zero+code%3A+137&aqs=chrome..69i57.727j0j1).  Are you running an entry-level Linux host on a cloud provider?  If so, is there any particular reason you copied your app to another machine to run the build?  You can run `docker build` right from your macOS development environment and accomplish the same thing (without dealing with the limited memory/cpu issues you get on a budget cloud server).

My recommendation is to try running again on your local machine.

**Comment by nzwade** [comment]
Thanks very much @jshimko, I was using a 512mb digital ocean host and even after adding a swap file I still hit this error. What worked for me was as you said, installing Docker on my Mac and building the image there. I then transferred the docker image to my production environment using `docker save <image> | bzip2 | ssh user@host 'bunzip2 | docker load'`
