### ISSUE TITLE
Add support for phantomjs ?

### ISSUE THREAD

**Issue by virtuman** [jshimko/meteor-launchpad#3]
would you consider adding support for phantomjs?
https://github.com/meteorhacks/meteord/blob/master/base/scripts/lib/install_phantomjs.sh

maybe along with 2.1.1 instead of 1.9.8 ? or a customizable ENV for phantomjs version number?

**Comment by jshimko** [comment]
Sure.  I already have the script written actually.  I just haven't pushed it up.  Also, I want it to be optional (so it won't be a part of the image unless you opt-in to install it with an env var).  Not everybody needs it and that'd be extra bloat in the image if you weren't actually using it.

Give me a day or so and I'll get it published.

**Comment by jshimko** [comment]
Installing Phantom is now an available option (not installed by default).  See the updated docs...

https://github.com/jshimko/meteor-launchpad#custom-build-options

In short, create a `launchpad.conf` in the root of your app and add the following to it...

``` sh
INSTALL_PHANTOMJS=true
```

When you build your container, Phantom will then be installed (2.1.1 is the default).  You can also define the Phantom version in your config file with `PHANTOM_VERSION=x.x.x`

Let me know if you run into any issues.
