### ISSUE TITLE
readFilesync of undefined when building Meteor docker image on Jenkins

### ISSUE THREAD

**Issue by sishengz** [jshimko/meteor-launchpad#31]
Docker Version: 1.6.0
Jenkins Version: 2.19.3

When building our docker image on Jenkins, we get the following error.

[91minfo�[0m�[91m �[0m�[91merror reading version TypeError: Cannot read property 'readFileSync' of undefined
�[0m�[91minfo error reading version at /root/.meteor/packages/meteor-tool/.1.4.1_3.8dq62w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:42:24
�[0m�[91minfo error reading version�[0m�[91m at Object. (/root/.meteor/packages/meteor-tool/.1.4.1_3.8dq62w++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/cordova-lib/node_modules/npm/lib/npm.js:475:3)

**Comment by jshimko** [comment]
I noticed you reported the same issue at the meteord repo.  I'm inclined to think it's something to do with your app or build environment and not the base container.  Can you provide a public repo that reproduces this issue?  I won't be able to provide much help without being able to see the issue happen locally.

Also, Docker 1.6.0???  That's a SUPER old version (released in April 2015).  Docker is at 1.12.x at this point.
