### ISSUE TITLE
Directory not empty error - build.sh

### ISSUE THREAD

**Issue by michaeljquinn** [jshimko/meteor-launchpad#33]
Virtualbox hosting RHEL 7.2 (latest)
Docker version 1.13.0, build 49bf474
build.sh - post-install-cleanup.sh is failing with "Directory not empty"

**Comment by jshimko** [comment]
Can you be more specific about what you've tried?  Many people use this project every day without issues.  Ideally, can you provide a repo that reproduces the issue?

**Comment by michaeljquinn** [comment]
Jeremy

 

                Different error now (note I did not run build.sh) – see output log

Error: EXDEV: cross-device link not permitted, rename '/opt/meteor/dist/bundle' -> '/opt/meteor/dist/bundle-garbage-1nof7ku'

 

                My environment is

 

                Virtualbox                                           : 5.1.10 r112026 (Qt5.6.2)

                Windows 10 host                             : 10.0.14393 Build 14393

                Virtual Box VM                                  :  Red Hat Enterprise Linux : 7.2

   3.10.0-514.6.1.el7.x86_64 #1 SMP Sat Dec 10 11:15:38 EST 2016 x86_64 x86_64 x86_64 GNU/Linux

Running docker

                Virtual Box VM settings :              : 5112MB

                                                                                  2CPU

                                                                                  40GB – dynamic –currently 5GB

                                                                                   NAT adapter

                                                                                   Host Only adapter

 

                

                Process: 

Clean environment

                                Downloaded meteor-todo-master : https://github.com/meteor/simple-todos

                                unzip simple-todos-master.zip into the /home/dpdev/Docker/Meteor/simple-todos-master directory

 

                                current dir is /home/dpdev/Docker/Meteor/simple-todos-master/simple-todos-master

 

                     drwxrwxr-x. 2 dpdev dpdev     51 Aug  1  2016 client

drwxrwxr-x. 5 dpdev dpdev     39 Aug  1  2016 imports

-rw-rw-r--. 1 dpdev dpdev   1198 Aug  1  2016 LICENSE

-rw-rw-r--. 1 dpdev dpdev    153 Aug  1  2016 package.json

-rw-rw-r--. 1 dpdev dpdev    438 Aug  1  2016 README.md

-rw-rw-r--. 1 dpdev dpdev 233688 Aug  1  2016 screenshot.png

drwxrwxr-x. 2 dpdev dpdev     20 Aug  1  2016 server 

 

Created dockerfile

drwxrwxr-x. 2 dpdev dpdev     51 Aug  1  2016 client

-rw-rw-r--. 1 dpdev dpdev     33 Feb  2 09:12 Dockerfile

drwxrwxr-x. 5 dpdev dpdev     39 Aug  1  2016 imports

-rw-rw-r--. 1 dpdev dpdev   1198 Aug  1  2016 LICENSE

-rw-rw-r--. 1 dpdev dpdev    153 Aug  1  2016 package.json

-rw-rw-r--. 1 dpdev dpdev    438 Aug  1  2016 README.md

-rw-rw-r--. 1 dpdev dpdev 233688 Aug  1  2016 screenshot.png

drwxrwxr-x. 2 dpdev dpdev     20 Aug  1  2016 server                    

 

[dpdev@dockerpp simple-todos-master]$ cat Dockerfile 

FROM jshimko/meteor-launchpad:latest

 

[dpdev@dockerpp simple-todos-master]$ pwd

/home/dpdev/Docker/Meteor/simple-todos-master/simple-todos-master             

 

docker build -t dpdev/simpletodo . > output 2>&1

**Comment by michaeljquinn** [comment]
Jeremy

 

                At the end

                Docker images shows

 

REPOSITORY                 TAG                 IMAGE ID            CREATED             SIZE

<none>                     <none>              d38974e898c3        14 minutes ago      356 MB

jshimko/meteor-launchpad   latest              c7b9579894ad        6 weeks ago         356 MB

**Comment by jshimko** [comment]
Is there any reason you're not using the provided build environment that comes with a standard Docker install?  Why specifically a RedHat VM?  If I had to guess (which I do), I'd say your build environment has something to do with this.  

What happens if you try to build without manually running a Virtualbox VM?

**Comment by jshimko** [comment]
I'm going to assume this isn't an issue with this project for now, but feel free to open it again if you believe otherwise.
