### ISSUE TITLE
Add TOOL_NODE_FLAGS setting

### ISSUE THREAD

**Issue by krismeister** [jshimko/meteor-launchpad#41]
We're running into an issue with the build process running out of memory, as described here: https://github.com/meteor/meteor/issues/8157

The fix appears to set an `ENV`
```
TOOL_NODE_FLAGS="--max-old-space-size=4096 --optimize_for_size --gc-interval=100"
```
Which gets used inside Meteor's node build command.

It would be helpful if there was an option to set this in meteor-launchpad.

**Comment by jshimko** [comment]
Sounds reasonable.  Have you confirmed that adding that fixes the problem for you?  I see several people in that issue saying it didn't work for them.

**Comment by krismeister** [comment]
```bash
# in base.dockerfile
ENV TOOL_NODE_FLAGS=--max-old-space-size=2048
```
Did work for me - I assume increasing even further or adding garbage collection flags could help others.

**Comment by jshimko** [comment]
Ok, `v1.2.0` has added the option to use Docker's `--build-arg` flag to set that environment variable.  You can now set that to anything you want at build time like this:

```sh
docker build --build-arg TOOL_NODE_FLAGS="--max-old-space-size=2048" -t myorg/myapp:latest .
```  

Let me know if that does the trick for you.

**Comment by kachizukanne** [comment]
This fix seems to break builds that aren't currently using this flag
![image](https://cloud.githubusercontent.com/assets/2982953/26505221/d239c6cc-423f-11e7-8004-c4a93ef35d89.png)

Please have a look to check if this experience is consistent across board

**Comment by jshimko** [comment]
@kachizukanne What version of Docker are you running?  `ARG` wasn't added until somewhere around v1.9.x.  That's the exact error I've seen when running Docker 1.8, so I'm assuming that's likely to be your issue.

**Comment by kachizukanne** [comment]
Spot on, upgrading docker to a post 1.8 version fixed this

**Comment by jshimko** [comment]
I'm going to assume this is working for everyone and close this issue.  Feel free to reopen if there's an issue related to these changes.

Also, note the new build arg options that were just added in v1.3.0

https://github.com/jshimko/meteor-launchpad#build-options

**Comment by wchen99998** [comment]
The issue remains
