### ISSUE TITLE
Custom docker image names not using correct base image

### ISSUE THREAD

**Issue by krismeister** [jshimko/meteor-launchpad#43]
Per the instructions:

```bash
# or specify a custom image name
./build.sh myorg/myimage
```
Does not respect the docker base images inside of dev.dockerfile and prod.dockerfile.

https://github.com/krismeister/meteor-launchpad/blob/master/dev.dockerfile#L1
https://github.com/krismeister/meteor-launchpad/blob/master/prod.dockerfile#L1

Expected result:
prod.dockerfile & dev.dockerfile uses the new custom base image `myorg/myimage:base`

ps: this was a very tricky issue to find, I built many times before understanding what was happening.

**Comment by jshimko** [comment]
The v2 release has done away with the base image and now uses to two totally separate Dockerfiles for the two builds, so this should be all set now.

Thanks for filing the issue!

**Comment by jshimko** [comment]
Also, since there's no base image to build first, you can just run this now...

```sh
docker built -t whatever/you:want .
```

**Comment by krismeister** [comment]
thanks!
