### ISSUE TITLE
reading of the launchpad.conf file

### ISSUE THREAD

**Issue by mickaEkino** [jshimko/meteor-launchpad#44]
First, big thanks for the image.
I noticed that your latest modifications of the image impact on the reading of the launchpad.conf file. Indeed, when I run a container using the latest image I get a mongoDB URL error ( although I've set INSTALL_MONGO=true in the launchpad.conf file), when I use the previous version of the image (v1.2.0) everything is OK.

Thanks again.

**Comment by jshimko** [comment]
Sorry for the inconvenience.  I'll take a look at it later today.  In the meantime, you can also use `--build-arg` flags to get the old behavior back.

```sh
docker build --build-arg INSTALL_MONGO=true -t myorg/myapp:latest .
```

**Comment by jshimko** [comment]
@mickaEkino This should be fixed in `v2.x.x` 

Pull the latest build and give it another try.

**Comment by mickaEkino** [comment]
Sorry I've just seen your answer now (busy last day). It's perfect, thanks !

**Comment by jshimko** [comment]
Thanks for update!
