### ISSUE TITLE
About oplog

### ISSUE THREAD

**Issue by crapthings** [jshimko/meteor-launchpad#5]
hi i'm not experienced in docker, i wonder should i set oplog inside docker by myself

**Comment by jshimko** [comment]
Oplog doesn't come from your app container.  It's from your Mongo deployment.  You can add oplog tailing to any Meteor app by setting the `MONGO_OPLOG_URL` environment variable.

https://docs.mongodb.com/v3.2/core/replica-set-oplog/

https://themeteorchef.com/snippets/setting-up-mongodb-oplog-tailing/
