### ISSUE TITLE
meteor 1.2.1 E: The method driver /usr/lib/apt/methods/https could not be found.

### ISSUE THREAD

**Issue by hanselke** [jshimko/meteor-launchpad#50]
RUN cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh && 		$BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh
 ---> Running in a51f5b01b87f

[-] Installing base OS dependencies...

E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c cd $APP_SOURCE_DIR &&             $BUILD_SCRIPTS_DIR/install-deps.sh &&             $BUILD_SCRIPTS_DIR/install-node.sh &&             $BUILD_SCRIPTS_DIR/install-phantom.sh && 						$BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&             $BUILD_SCRIPTS_DIR/install-mongo.sh &&             $BUILD_SCRIPTS_DIR/install-meteor.sh &&             $BUILD_SCRIPTS_DIR/build-meteor.sh &&             $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 100

**Comment by jshimko** [comment]
This appears to be a rare edge case when an `apt` mirror gets redirected to an https source instead.  (I'm assuming you haven't added custom packages)

https://unix.stackexchange.com/questions/263801/apt-get-fails-the-method-driver-usr-lib-apt-methods-https-could-not-be-found

Version 2.0.3 should fix this.  (trying to rerun the build probably would've fixed it too, but at least now it's covered).  Please let me know if that solves it for you.

**Comment by jshimko** [comment]
This should be fixed now.  Feel free to reopen the issue if you experience this problem again.
