### ISSUE TITLE
Pull request for using APT_GET_INSTALL not merged

### ISSUE THREAD

**Issue by mklueh** [jshimko/meteor-launchpad#52]
I was trying to use APT_GET_INSTALL in my launchpad.conf because I needed libssl-dev and was wondering why it ignores the command.

It seems that the REAMDE.md is updated and contains explanation of this functionality, but the pull request #40 is still not merged and the functionality is missing.

Besides that the config is not "APT_GET_INSTALL", but "INSTALL_APTGET_PACKAGES"

**Comment by jshimko** [comment]
I think you might be missing something in your logs because it works fine for me.  And I didn't merge that pull request because I wrote the code for that functionality myself.  I'm also 100% positive it's `APT_GET_INSTALL`.

I just ran this and got the expected results with no issues...

```
docker build --build-arg APT_GET_INSTALL="libssl-dev" -t myorg/myapp:latest .
```

**Comment by jshimko** [comment]
I apologize... it looks like I didn't add support for using that from the `launchpad.conf` file.  I just added it in v2.0.4, so you should be all set once pulling the latest.
