### ISSUE TITLE
OS X and iOS build on Linux?

### ISSUE THREAD

**Issue by joshuacox** [jshimko/meteor-launchpad#54]
Of note, I do note want to build iOS apps in Linux, that is merely the strange error I get when building, same on [dockerhub](https://hub.docker.com/r/webhostingcoopteam/todos/builds/bbdlrevrdzstny4afhkncrd/):

```
 [91mCurrently, it is only possible to build iOS apps on an OS X system. [0m [91mSupply the server hostname and port in the --server option for mobile app builds. 
```

Have I done something wrong?  I am adapting this to the `meteor create --example todos` example meteor project.  I have only created the `Dockerfile` and `.dockerignore` files.  Branch [here](https://github.com/WebHostingCoopTeam/todos/tree/dockerfile)

**Comment by jshimko** [comment]
This should be fixed in `v2.1.1`.  Please give it a test and let me know.
