### ISSUE TITLE
Can´t run build.sh on Windows 10

### ISSUE THREAD

**Issue by mklueh** [jshimko/meteor-launchpad#56]
Me again.

I´m trying to create a custom image in order to make meteor-launch not the base layer anymore, because I want to speed up the build process. It seems that it doesn´t work on Windows 10.

This is the log

>  ---> 49b198f9b174
> Removing intermediate container d31191409055
> Step 15/42 : RUN bash $BUILD_SCRIPTS_DIR/install-deps.sh &&             bash $BUILD_SCRIPTS_DIR/post-install-cleanup.sh
>  ---> Running in affae9705315
> /opt/build_scripts/install-deps.sh: line 2: $'\r': command not found
> : invalid optionts/install-deps.sh: line 3: set: -
> set: usage: set [-abefhkmnptuvxBCHP] [-o option-name] [--] [arg ...]
> /opt/build_scripts/install-deps.sh: line 4: $'\r': command not found
> 
> [-] Installing base OS dependencies...
> 
> /opt/build_scripts/install-deps.sh: line 6: $'\r': command not found
> /opt/build_scripts/install-deps.sh: line 8: $'\r': command not found
> E: Invalid operation update
> /opt/build_scripts/install-deps.sh: line 10: $'\r': command not found
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Unable to locate package apt-transport-https
> E: Unable to locate package ca-certificates
> /opt/build_scripts/install-deps.sh: line 14: $'\r': command not found
> /opt/build_scripts/install-deps.sh: line 46: syntax error: unexpected end of file
> The command '/bin/sh -c bash $BUILD_SCRIPTS_DIR/install-deps.sh &&              bash $BUILD_SCRIPTS_DIR/post-install-cleanup.sh' returned a non-zero code: 2
> 

Is it possible to build that image on Windows somehow?

**Comment by jshimko** [comment]
I have no idea what you've done here.  Can you provide some code or a repo?  And what part of the build are you thinking will go faster by doing whatever you're trying here?
