### ISSUE TITLE
Adjust key servers to support corporate firewalls

### ISSUE THREAD

**Issue by sebakerckhof** [jshimko/meteor-launchpad#58]
Many corporate networks will block outgoing port `11371`, which is by default used when contacting keyservers.

Our builds are also failing because of this. The default solution is to use a keyserver on port 80.
E.g. replace `ha.pool.sks-keyservers.net ` with `hkp://p80.pool.sks-keyservers.net:80`

here: https://github.com/jshimko/meteor-launchpad/blob/34d97b4f834f238cdf69cab71457dbf9540a6a39/scripts/install-deps.sh#L36

and here: https://github.com/jshimko/meteor-launchpad/blob/e2695536e0338d7812776432be2712ad303ad2a7/scripts/install-mongo.sh#L12

**Comment by jshimko** [comment]
Fixed via #59 

Thanks @sebakerckhof!

**Comment by jshimko** [comment]
This has been released in `v2.1.3` (also currently `:latest`)
