### ISSUE TITLE
Error: Module did not self-register.

### ISSUE THREAD

**Issue by xwilders** [jshimko/meteor-launchpad#6]
I was using your excellent meteord image; the build failing (saying image not found) brought me here to try meteor-launchpad.

My app builds correctly, but when launched on staging I get:

> 25/10/2016 23:04:02Error: Module did not self-register.
> 25/10/2016 23:04:02    at Error (native)
> 25/10/2016 23:04:02    at Object.Module._extensions..node (module.js:434:18)
> 25/10/2016 23:04:02    at Module.load (module.js:343:32)
> 25/10/2016 23:04:02    at Module.Mp.load (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/babel-compiler/node_modules/reify/node/runtime.js:16:23)
> 25/10/2016 23:04:02    at Function.Module._load (module.js:300:12)
> 25/10/2016 23:04:02    at Module.require (module.js:353:17)
> 25/10/2016 23:04:02    at require (internal/module.js:12:17)
> 25/10/2016 23:04:02    at bindings (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:76:44)
> 25/10/2016 23:04:02    at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/npm/node_modules/meteor/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
> 25/10/2016 23:04:02    at Module._compile (module.js:409:26)
> 25/10/2016 23:04:04=> Starting app on port 80...
> 25/10/2016 23:04:09/opt/meteor/dist/bundle/programs/server/node_modules/fibers/future.js:280
> 25/10/2016 23:04:09                       throw(ex);

**Comment by jshimko** [comment]
Sorry to hear about the issue with my old MeteorD image.  I didn't realize other people were using it.  I recently deleted the image from Docker Hub because I haven't updated it in about 6 months and MeteorD seems to have been abandoned.  I decided a while back that if I'm going to use a base image for my production builds, I need to know it's actually maintained.  That said, I ended up building my own from scratch.

As for your issue, I don't know.  I've never seen that before.  If you have a public repo that can reproduce the problem, I'd be happy to take a look at it.

**Comment by xwilders** [comment]
As you say, MeteorD is (sadly) no longer maintained. I've been jumping around images, my Dockerfile currently looks like this:

```
FROM jshimko/meteor-launchpad:latest

# FROM jshimko/meteord:onbuild
# FROM markoshust/meteor:0.10.45
# FROM jacobdr/meteord:onbuild
# FROM ulexus/meteor:latest
# FROM meteorhacks/meteord:onbuild
# FROM quay.io/chriswessels/meteor-tupperware
```

I haven't yet made the jump to Meteor 1.4, I guess that might be the issue with this new image. I'll try updating to 1.4. Either that, or I'll make my own image. Thanks for your help.

**Comment by jshimko** [comment]
Yeah, if you aren't using Meteor 1.3 or higher, this project definitely won't work for you.  And if you don't want to always be on the latest release of Meteor, this image may not be for you.  I keep this project updated to always support the latest stable version of Meteor and the version of Node that it supports.
