### ISSUE TITLE
How to enable DDP Connections?

### ISSUE THREAD

**Issue by enzolutions** [jshimko/meteor-launchpad#64]
Hi @jshimko  

I am using this image through the project http://meteor-up.com/ and works perfectly.

The only thing I am missing now is how to enable DDP connection from external applications using DDP Clients.

Any recommendation?

**Comment by jshimko** [comment]
This doesn't really have anything to do with this project, so I'm going to have to recommend you check out a few other resources. You may want to check out the [official docs for DDP](https://docs.meteor.com/api/connections.html) or do a search for the various DDP clients (if you're not using a Meteor app for the remote client).

https://docs.meteor.com/api/connections.html

https://www.npmjs.com/package/ddp-client

**Comment by enzolutions** [comment]
HI @jshimko 

Thanks for your quick response, I don't have problems with the client in my local works but is on the server when I cannot connect, so I imagine maybe wrong that is something related with docker ports security or redirection.

Kind regards
