### ISSUE TITLE
Docker build of meteor-launchpad:devbuild fails on Windows 10 Pro 64-bit: "You're not in a Meteor project directory"

### ISSUE THREAD

**Issue by SebastianSativa** [jshimko/meteor-launchpad#67]
When i try to build meteor-launchpad:devbuild in Docker on windows 10 pro 64-bit, I get this error:

![image](https://user-images.githubusercontent.com/9719427/30824813-04190666-a231-11e7-9c81-bbffc992373c.png)

**Comment by jshimko** [comment]
This error only happens when you're not in a Meteor directory.

**Comment by SebastianSativa** [comment]
Where in your documentation does it say that I should be in a meteor app directory in order to build from your Docker image? Because all I did was jump into the console and attempt to build a Docker image from a file with the line `FROM jshimko/meteor-launchpad:devbuild`

**Comment by jshimko** [comment]
If you're not using it to build a Meteor app, what is it that you're expecting this image to do for you?  That is literally the _only_ thing this project is for.

<img width="789" alt="jshimko_meteor-launchpad__a_base_docker_image_for_meteor_applications_" src="https://user-images.githubusercontent.com/3077956/30919542-b476deea-a36f-11e7-9dbb-fdb5796a1737.png">

First two lines of the readme...

<img width="906" alt="jshimko_meteor-launchpad__a_base_docker_image_for_meteor_applications_" src="https://user-images.githubusercontent.com/3077956/30919623-f3f580e4-a36f-11e7-99bd-7e2b8938aa75.png">

**Comment by SebastianSativa** [comment]
Right! I totally see what you're saying now. Sorry for letting the stress get to my head there :)

**Comment by jshimko** [comment]
No worries.  :)
