### ISSUE TITLE
Downloading meteor distribution fails

### ISSUE THREAD

**Issue by Gimly** [jshimko/meteor-launchpad#68]
I'm trying to run the `docker build -t` command and I'm getting an issue when starting the "Installing Meteor" step.

```
... Installing Meteor 1.5.2

Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```

It looks like it cannot connect to download the meteor distribution, but all the other commands that require access to the internet are working fine (apt-get, etc.).

My Dockerfile has just the `FROM jshimko/meteor-launchpad:latest` in it, and I have no launchpad.conf.

Thanks in advance for your help.

**Comment by jshimko** [comment]
That's usually from a network error with Meteor's CDN and trying again often resolves it.  You could also try running that same install script outside of the container to confirm it works.

(if you're on Mac/Linux)
```sh
curl https://install.meteor.com/ | sh
```

**Comment by Gimly** [comment]
I tried already a few times and still the same result. I tried to do a `docker -it debian:jessie` and then launch the install meteor script from there and it works fine.

**Comment by jshimko** [comment]
Are there any other errors earlier in the logs?  I use this image every day on several projects and don't ever have this issue.  I'm wondering if there's something specific about your app.  If you have a repo that can reproduce this issue, I'd be happy to take look.

**Comment by Gimly** [comment]
OK, I think I figured it out, it was the version of Meteor, the `release` file had the Meteor version 1.5.2, updated to 1.5.2.2 and it's installing meteor correctly.

Now I have another issue... here's the output I'm getting:

```
/root/.meteor/packages/meteor-tool/.1.5.2_2.fkst7p++os.linux.x86_64+web.browser+web.cordova/mt-os.linux.x86_64/dev_bundle/lib/node_modules/meteor-promise/promise_server.js:218
      throw error;
      ^

Error: EISDIR: illegal operation on a directory, unlink '/opt/meteor/src/.meteor/local/dev_bundle'
    at Error (native)
    at Object.fs.unlinkSync (fs.js:932:18)
    at exports.makeLink (/tools/cli/dev-bundle-links.js:20:8)
    at [object Object]._.extend.ensureDevBundleLink (/tools/project-context.js:1509:7)
    at [object Object]._.extend._readFile (/tools/project-context.js:1443:10)
    at new exports.ReleaseFile (/tools/project-context.js:1393:8)
    at /tools/cli/main.js:898:22
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
```

And I have the same error on a freshly created Meteor app.

**Comment by Gimly** [comment]
Nevermind, solution was in the error message, I had to remove the symlink to dev_bundle in the .meteor/local folder.

It's working now, thanks !

**Comment by jshimko** [comment]
No prob.  Glad you figured it out!

**Comment by jshimko** [comment]
For what it's worth, you may want to add `.meteor/local` to your `.dockerignore` file.  That isn't needed inside the container and that avoids passing in previous builds that were done on a different machine (your laptop vs the Debian OS in the image).  That way you can always be sure what builds in the container is a completely fresh build with no previous cache.

**Comment by kletkeman** [comment]
And a year later the same thing happens for me ... out of 5 Meteor base loads I have tried, I've had the most success with this one. But last night this same issue cropped up and I've checked to see that 1.8 has not been superseded, and I can only see betas and release candidates ahead of it, so I am wondering if anyone knows what is going on?

```
100  7782    0  7782    0     0  35115      0 --:--:-- --:--:-- --:--:-- 35212
* Connection #0 to host install.meteor.com left intact

... Installing Meteor 1.8

Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
PS C:\users\kim\dev\projects\wsas\wsas_controller>
```
Tagging @jshimko
