### ISSUE TITLE
Docker Image Won't build - Downloading Meteor despite it was already downloaded

### ISSUE THREAD

**Issue by badmark** [jshimko/meteor-launchpad#70]
Cannot get past the meteor download of the Docker image build. Unlike other issue, the version is being found, just not downloading; any ideas?

`node-v4.8.4-linux-x64/lib/node_modules/npm/node_modules/umask/.npmignore
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
**100  7786    0  7786    0     0  44481      0 --:--:-- --:--:-- --:--:-- 44747** <--- Seems to suggest the download occured

... Installing Meteor 1.5.2.2

Downloading Meteor distribution
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
Retrying download in 5 seconds...
The command '/bin/sh -c cd $APP_SOURCE_DIR &&   $BUILD_SCRIPTS_DIR/install-deps.sh &&   $BUILD_SCRIPTS_DIR/install-node.sh &&   $BUILD_SCRIPTS_DIR/install-phantom.sh &&   $BUILD_SCRIPTS_DIR/install-graphicsmagick.sh &&   $BUILD_SCRIPTS_DIR/install-mongo.sh &&   $BUILD_SCRIPTS_DIR/install-meteor.sh &&   $BUILD_SCRIPTS_DIR/build-meteor.sh &&   $BUILD_SCRIPTS_DIR/post-build-cleanup.sh' returned a non-zero code: 1
`

**Comment by 2-towns** [comment]
Hi,

How did you solved this problem ?

**Comment by Sandiejat** [comment]
We moved a few repositories around and had this issue for all of the projects. Once the meteor project is created in the new location, the build succeeded for all of them.
It can happen if the project is moved/copied from another location. If that's the case, a meteor project has to be created again in the new location.

**Comment by pedrolucasoliva** [comment]
@Sandiejat, means I need recreate the project?
