### ISSUE TITLE
Dont upload .meteor/local when building

### ISSUE THREAD

**Issue by aviadbd** [jshimko/meteor-launchpad#71]
It seems that every time I build, a huge upload takes place. This is due to the .meteor/local folder, it seems, as the build process uploads all the files in the local directory, including that. 

Is it possible NOT to upload it? After all, it's not used.

**Comment by aviadbd** [comment]
I believe just adding the dir to .dockerignore should do the trick?

**Comment by jshimko** [comment]
Yes.  Here's a recommended starting point for your `.dockerignore`

```
.git
.meteor/local
node_modules
```

None of those large directories are needed inside your docker build and ignoring them will make the initial copy of files much faster.

**Comment by aviadbd** [comment]
Maybe its best to have a repo to download the basic Dockerfile and .dockerignore files. Would make everyone's lives easier.

**Comment by jshimko** [comment]
I think a readme update is probably plenty for that (and I just did it).  I'd rather not have to maintain a repo with 2 files and 4 total lines of text.  The readme already gives you the single line you need to add to your Dockerfile and now it has notes about setting up a dockerignore file (see first "Build" section).
