### ISSUE TITLE
NODE_VERSION in launchpad.conf isn't being used.

### ISSUE THREAD

**Issue by luzlab** [jshimko/meteor-launchpad#72]
I tried specifying NODE_VERSION in the launchpad.conf, but it only works when specified as a build-arg.

Looking at he code for [install.node.sh](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/install-node.sh#L5), it seems like the code to load the NODE_VERSION from the launchpad.conf is missing.

```javascript
if [ -f $APP_SOURCE_DIR/launchpad.conf ]; then
  source <(grep NODE_VERSION $APP_SOURCE_DIR/launchpad.conf)
```

**Comment by jshimko** [comment]
This was fixed by #74 (thanks @luzlab!) and was released in `v2.2.2`
