### ISSUE TITLE
Support for Meteor 1.6

### ISSUE THREAD

**Issue by aviadbd** [jshimko/meteor-launchpad#78]
I think that since Meteor 1.6 updated NPM and NodeJS, the defaults for those should change (or at least take the Meteor version installed into consideration).

**Comment by jshimko** [comment]
The latest release (v2.3.0) now supports Meteor 1.6.

FYI, this image _does_ take the Meteor version into consideration.  It specifically [installs the version your app uses](https://github.com/jshimko/meteor-launchpad/blob/master/scripts/install-meteor.sh#L11-L26).  The main issue was Node 8 was not being installed by default.  But you can also override that as well with `--build-arg NODE_VERSION=8.9.0` when building your image.  See [this section of the readme](https://github.com/jshimko/meteor-launchpad#build-options) for more info on that.

Either way, you should be good to go now!
