### ISSUE TITLE
node-fibers is missing

### ISSUE THREAD

**Issue by aleksander351** [jshimko/meteor-launchpad#92]
After running my docker-compose.yml, I get:

app_1    | => Starting app on port 3000...
app_1    | ## There is an issue with `node-fibers` ##
app_1    | `/opt/meteor/dist/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.
app_1    |
app_1    | Try running this to fix the issue: /opt/nodejs/bin/node /opt/meteor/dist/bundle/programs/server/node_modules/fibers/build
app_1    | /opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:20
app_1    |      throw new Error('Missing binary. See message above.');
app_1    |      ^
app_1    |
app_1    | Error: Missing binary. See message above.
app_1    |     at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:20:8)
app_1    |     at Module._compile (module.js:635:30)
app_1    |     at Object.Module._extensions..js (module.js:646:10)
app_1    |     at Module.load (module.js:554:32)
app_1    |     at tryModuleLoad (module.js:497:12)
app_1    |     at Function.Module._load (module.js:489:3)
app_1    |     at Module.require (module.js:579:17)
app_1    |     at require (internal/module.js:11:18)
app_1    |     at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/boot.js:1:75)
app_1    |     at Module._compile (module.js:635:30)

There is this suggestion:
"Node fibers have to be re-installed after unpacking the bundle. To fix this problem go to the server directory: bundle/programs/server"

I can not access /opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js 
Do I have to go into the image volume?

**Comment by jshimko** [comment]
I've never seen that before.  Looks like the binary build for fibers failed.  Have you tried just creating a new build of your image?

**Comment by Arsey** [comment]
same issue for me. I've tried to build from scratch, not helped.


```
[-] External MONGO_URL not found. Starting local MongoDB...


[-] External MONGO_URL not found. Starting local MongoDB...

=> Starting app on port 3000...
## There is an issue with `node-fibers` ##
`/opt/meteor/dist/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.

Try running this to fix the issue: /opt/nodejs/bin/node /opt/meteor/dist/bundle/programs/server/node_modules/fibers/build
/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:20
        throw new Error('Missing binary. See message above.');
        ^

Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:635:30)
```

**Comment by aleksander351** [comment]
Hi, thank you for the reply.

It failed with jshimko/meteor-launchpad:latest
but succeeded with jshimko/meteor-launchpad:devbuild

..so I am sticking with that for now.
2 questions though. The built image is about 3 GB large. Is that normal?
And second question: What is the best procedure for updating the application? Removing existing image and rebuilding it with the updated app? Could be added to the readme file.

Another problem just occured, Did not build the new image successfully. Temporary containers not stopped and removed and image name not set. May be low RAM problem. Will retry now.

**Comment by jshimko** [comment]
I can't reproduce this issue.

```sh
meteor create mytest
cd mytest

echo "FROM jshimko/meteor-launchpad:latest" > Dockerfile

docker build -t mytest .
```
No errors and the image runs.

If you can provide a public repo for me to look at, I'd be happy to take a look.  Not sure what else to recommend though.

**Comment by jshimko** [comment]
@aleksander351 see the notes on the devbuild in the readme.

https://github.com/jshimko/meteor-launchpad#development-builds

> This isn't recommended for your final production build because it creates a much larger image, but it's a bit of a time saver when you're building often in development. The first build you run will download/install Meteor and then every subsequent build will be able to skip that step and just build the app.

It makes a huge image because all of the build tools and Meteor are cached in the image.  That's not the case with the regular build.  It cleans up everything that isn't used after the build is complete.

**Comment by aleksander351** [comment]
Oh I see. I will try to build the "development" image and later the "latest" again.
I will come back with updates ASAP.

**Comment by aleksander351** [comment]
Now I get:

Unable to resolve some modules:

  "try-thread-sleep" in
/opt/meteor/src/node_modules/spawn-sync/lib/spawn-sync.js (web.browser)

If you notice problems related to these missing modules, consider running:

  meteor npm install --save try-thread-sleep

/opt/build_scripts/build-meteor.sh: line 27:    42 Killed                  meteor build --directory $APP_BUNDLE_DIR --server-only
The command '/bin/sh -c bash $BUILD_SCRIPTS_DIR/build-meteor.sh' returned a non-zero code: 137

Build fails now probably due to some problems in my application.

**Comment by aleksander351** [comment]
Ok, I made some changes to my app, ran "devbuild" and "latest" again and it works now. Might be also RAM issues, Have 1 GB dedicated for now.

**Comment by Netherdrake** [comment]
I am running into the same issue with `meteor-launchpad:latest` and `Meteor 1.4.4.2`. Tried removing the image and installing from scratch, no luck.

**Comment by xquadradpi** [comment]
im running the same issue
any working way to fix this?
Could it be a package or version problem?

**Comment by korenlev** [comment]
same issue here, image is built, crash when running, log:
Error: Missing binary. See message above.
    at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/node_modules/fibers/fibers.js:20:8)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/meteor/dist/bundle/programs/server/boot.js:1:75)
    at Module._compile (module.js:635:30)
=> Starting app on port 3000...
## There is an issue with `node-fibers` ##
`/opt/meteor/dist/bundle/programs/server/node_modules/fibers/bin/linux-x64-57/fibers.node` is missing.

**Comment by korenlev** [comment]
i have managed to re-produce on one server and not on another, here is my determination:
4.4.0-21-generic #37-Ubuntu, Docker version 17.03.1-ce, build c6d412e - builds ok, run ok
4.4.0-87-generic #110-Ubuntu, Docker version 17.06.0-ce, build 02c1d87 - build ok, run errors: node-fibers missing 

i hope it helps

**Comment by korenlev** [comment]
https://stackoverflow.com/questions/13327088/meteor-bundle-fails-because-fibers-node-is-missing
solved

**Comment by korenlev** [comment]
append to Dockerfile:
RUN cd /opt/meteor/dist/bundle/programs/server && npm uninstall fibers && npm install fibers

**Comment by korenlev** [comment]
more accurately (because initial build cleaned up node and  npm):
RUN apt-get -y update
RUN apt-get -y install sudo
RUN apt-get -y install curl
RUN apt-get -y install vim
RUN apt-get -y install net-tools
RUN curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
RUN sudo apt-get install -y nodejs
RUN cd /opt/meteor/dist/bundle/programs/server && npm uninstall fibers && npm install fibers

**Comment by korenlev** [comment]
now part of suggested-fixes pull requested :+1: https://github.com/jshimko/meteor-launchpad/pull/113/commits/da0c10fa99583b094d4313e46e51d05346b65a38
